platform:ios, '7.0'

inhibit_all_warnings!

pod 'SDWebImage', '~> 3.6'
pod 'JSQMessagesViewController'
#pod 'AOTutorial', '1.5'
pod 'Parse-iOS-SDK'
pod 'MFSideMenu'
pod 'APParallaxHeader'
pod 'iRate'
pod 'UINavigationBar+Addition'
pod 'IDMPhotoBrowser'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Reachability'
pod 'TITokenField'
#pod 'SWTableViewCell'
#pod 'MSCMoreOptionTableViewCell'
pod 'MagicalRecord'
pod 'pop', '~> 1.0.4'
#pod 'AFBlurSegue'