platform:ios, '7.0'

#pod 'AFNetworking'
pod 'JSMessagesViewController'
pod 'Facebook-iOS-SDK'
#pod 'EAIntroView'
pod 'AOTutorial'
#pod 'TWMessageBarManager', '~> 1.6.0'
pod 'TSMessages'
pod 'Parse-iOS-SDK'
pod 'MFSideMenu'