fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :app_store do
    match(type: "appstore")
    increment_build_number
    # snapshot
    gym(scheme: "VCinity", sdk: 'iphoneos') # Build your app - more options available
    testflight(changelog: "Change log", skip_waiting_for_build_processing: false)
    deliver(force: true, submit_for_review: true, skip_binary_upload: true, skip_screenshots: true, skip_metadata: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end